name: flutter_generator
description: A simple command-line application.
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  prompter_sg_null_safety: ^0.1.0
  path: ^1.9.0
  recase: ^4.1.0
  archive: ^3.5.1
dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.4.9

