name: flutter_generator
description: A simple command-line application.
environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  simple_prompter: ^2.2.1
  path: ^1.8.3
  recase: ^4.1.0
  archive: ^3.3.6
dev_dependencies:
  lints: ^2.0.1
  build_runner: 2.3.3

