// GENERATED CODE. DO NOT MODIFY. Generated by MyCustomRouterGenerator.

import 'package:teste/endpoints/usuario/usuario.dart';
import 'package:teste/endpoints/teste/teste.dart';
import 'package:teste/endpoints/root/root.dart';
import 'package:teste/endpoints/pagamento_sistema/pagamento_sistema.dart';
import 'package:teste/endpoints/login/login.dart';
import 'package:teste/endpoints/jwt/jwt.dart';
import 'package:teste/endpoints/imagem/imagem.dart';
import 'package:teste/endpoints/google_login/google_login.dart';
